let fruits = ["Apple", "Banana", "Mango"];
console.log(fruits);
console.log(fruits[0]);
console.log(fruits[1]);
fruits[1] = "Orange";
console.log(fruits);
let numbers = [10, 20, 30, 40];
console.log(numbers.length);
let colors = ["Red", "Blue"];
colors.push("Green");
colors.unshift("Yellow");
console.log(colors);
let nums = [5, 2, 8, 1];
nums.sort((a, b) => a - b);
console.log(nums);