let num = 10;
let str = "Hello";
let bool = true;
let empty = null;
let x;
let arr = [1, 2, 3];
let fruits = ["Apple", "Banana", "Mango"];
let bigNumber = 12345678901234567890n;
let value = null;
let age = 20;
let price = 99.99;
console.log(age);
console.log(price);
console.log(typeof age);
console.log(typeof price);
console.log(value);
console.log(typeof value);
console.log(bigNumber);
console.log(typeof bigNumber);
console.log(fruits);
console.log(typeof fruits);
console.log(typeof num);
console.log(typeof str);
console.log(typeof bool);
console.log(typeof empty);
console.log(typeof x);
console.log(typeof arr);
