let a = 10;
let b = 3;
console.log(a + b);
console.log(a - b); 
console.log(a * b); 
console.log(a / b);
console.log(a % b);
console.log(a ** b);
let c = 10;
let d = "10";
console.log(c == d);
console.log(c === d);
console.log(c != d);
console.log(c !== d);
console.log(c > 5);
console.log(c <= 10);
let num = 5;
console.log(num++);
console.log(num);
console.log(--num);
let e = 5;
let f = 1;
console.log(e & f);
console.log(e | f);
console.log(e ^ f);